- tools/test.py
in tools/test.py, lost one args "show_score_thr". 
```
if not distributed:
model = MMDataParallel(model, device_ids=[0])
outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
args.show_score_thr)
```
I search the project and find this in show_result(), and set default as 0.3.
> add show_score_thr.

- demo/demo_sot.py
Drawing a rectangle requires the thickness to be an integer, but the `arg.thickness `given is a string by default.
> fix draw rectangle

- mmtrack/models/mot/deep_sort.py
add support for one stage detector in DeepSORT simple_test function
> add support for one stage detector in DeepSORT simple_test function

- README.md
> add citation format

- mmtrack/utils/collect_env.py
- setup.cfg
- This PR updates [mmtracking/utils/collect_env.py](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/utils/collect_env.py) with [mmdetection/utils/collect_env.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/utils/collect_env.py) by utilizing [mmcv/collect_env](https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/env.py)
- It also adds windows support to [training script](https://github.com/open-mmlab/mmtracking/blob/master/tools/train.py)
> utilize mmcv collect_env (add windows support)

- configs/mot/deepsort/README.md
Fixed minor spelling mistake from 'basiclly' to 'basically'
> Spelling mistake

- mmtrack/models/backbones/sot_resnet.py
Fix a bug of the initialization method in sot resnet backbone, which caused by the refactor of mmdetection. For more information, please refer to open-mmlab/mmdetection#4750
> [Fix] fix a bug in sot resnet backbone

- mmtrack/core/evaluation/eval_hooks.py
- tests/test_data/test_dataset.py
Hi~
This PR fix the following bugs:
1. The `evaluation_flag` method in EvalHook has been replaced by  `_should_evaluate`.
2. The evaluation start epoch cannot be less than 0.
> [Fix] fix evaluation bug in eval_hooks.py

- docs/install.md
- requirements/runtime.txt
Hi~
This PR fix the compatibility bug of MMTracking, MMCV, and MMDetection version. Besides, MMClassification version is fixed at 0.12.0.
> [Fix] fix the compatibility bug of MMTracking, MMCV, and MMDetection version

- tools/convert_datasets/mot2reid.py
Hi~
This PR add a script which converts MOT dataset into ReID dataset. This is to prepare for reid training.
> [Feature] add the script which converts MOT dataset into ReID dataset.

- mmtrack/apis/train.py
- tools/test.py
- tools/train.py
Hi~
This PR add the add high level reid training api.
> [Feature] add high level reid training api

- configs/mot/deepsort/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py
- configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private-half.py
- mmtrack/models/reid/linear_reid_head.py
- tests/test_models/test_reid.py
This PR fix the following bug:
1. add `loss`  and `loss_pairwise` to mot config, the default is set to None. https://github.com/open-mmlab/mmtracking/pull/180#discussion_r659271518
2. use mmdet build_loss function. 
3. fix BaseReid model unitest
> [Fix] fix reid model unitest

- demo/demo_sot.py
- mmtrack/models/sot/base.py
This PR fixs the visualization in sot demo. In function `cv2.rectangle`, the coordinate points of the bbox need to be `np.int` instead of `np.float`. For more details, please refer to [here](https://docs.opencv.org/3.4/dc/da5/tutorial_py_drawing_functions.html).
> [Fix] fix visualization in sot demo

- mmtrack/apis/train.py
- mmtrack/models/__init__.py
- mmtrack/models/builder.py
- mmtrack/models/mot/deep_sort.py
- mmtrack/models/mot/tracktor.py
- mmtrack/models/vid/dff.py
- mmtrack/models/vid/fgfa.py
- mmtrack/models/vid/selsa.py
- requirements/runtime.txt
- tools/train.py
This PR supported to use MMCV registry ([#760](https://github.com/open-mmlab/mmcv/pull/760)) like MMDet did ([#5059](https://github.com/open-mmlab/mmdetection/pull/5059)).
> Use MMCV registry

- configs/sot/siamese_rpn/siamese_rpn_r50_1x_lasot.py
- mmtrack/apis/train.py
- mmtrack/core/evaluation/eval_hooks.py
- tools/train.py
This PR fixed several bugs to run MMTracking correctly.
It also changed the evaluation hook in siamese rpn config.
> Regression benchmark

- tools/train.py
Fix a bug where detector is not initialized when training a detector in MOT task.
The way to fix the bug may be a little ugly.
The reason is that MMDet has already supported unified model initialization, while MMTracking has not supported it. 
We will support it in the future.
> fix a bug where detector is not initialized when training a detector in MOT task

- configs/vid/temporal_roi_align/selsa_troialign_faster_rcnn_x101_dc5_7e_imagenetvid.py
- mmtrack/datasets/imagenet_vid_dataset.py
- mmtrack/datasets/parsers/coco_video_parser.py
- requirements/runtime.txt
As described in #259 , MMPycocotools is no longer necessary. We use the official pycocotools.
> Use pycocotools instead of mmpycocotools

- tools/mot_param_search.py
This PR solves bugs for ```mot_param_search.py``` following #265 and #266.
> [FIX] fix bugs in mot_param_search.py

- mmtrack/models/reid/base_reid.py
- requirements/runtime.txt
The type of output in the backbone of `mmcls >= 0.16.0` changes from `Tensor` to `(Tensor, )`.
This PR changes `base_reid.py` in order to adapt to mmcls >= 0.16.0.
> Adapt to mmcls >= 0.16.0

- mmtrack/datasets/coco_video_dataset.py
- setup.cfg
Just overloading the self.__repr__ in coco_video_dataset.py, the only changed line compared with CustomDatsaet.__repr__ is line 61.
For now, I can not generally fix the self.get_ann_info(dict) to self.get_ann_info(idx), cuz I'm not familiar with the tasks except for VID.
A better general way is reflecting the 'fetch idx' to 'img idx' before using self.get_ann_info()
In the VID dataset, key img info can only be fetched by 'fetch idx' from a filtered frame list, self.data_infos in which is_vid_train_frame = train.
While ref img can be sampled over all frames. So self.ref_img_sampling() can only return 'img idx'.
Both 'fetch idx' and 'img idx' use 'self.get_ann_info(idx)' could not work. I think that is the reason why change the parameters from idx to dict.
So build a index dict in …
> Fix coco video repr

- docs/dataset.md
- docs_zh-CN/dataset.md
- tools/convert_datasets/otb100/download_otb100.py
- tools/convert_datasets/otb100/otb2coco.py
Previous bbox coordinate converting can't parse the negative number coordinates.  We fix it. Please refer to https://github.com/open-mmlab/mmtracking/blob/master/tools/convert_datasets/otb100/otb2coco.py#L87
Please use the new script to convert OTB100 dataset, if you used it before.
> [Fix] fix a bug in the converting script of OTB100 dataset 

- docs/install.md
- setup.py
Related Issue: open-mmlab/mmdetection#6480
Creating a symbolic link on windows may raise an OSError: [WinError 1314] due to privilege. If the error happens, the src file will be copied.
> [Enhancement] Try to create a symbolic link on windows

- configs/_base_/default_runtime.py
- mmtrack/core/utils/__init__.py
- mmtrack/core/utils/misc.py
- tools/test.py
- tools/train.py
Reference: open-mmlab/mmdetection#6974 and open-mmlab/mmdetection#6867
> Accelerating training speed.

- mmtrack/models/trackers/byte_tracker.py
Fix a bug in `torch_full()` where the `dtype` must be specified in pt1.6.
> [Fix] fix the dtype bug in ByteTracker

- .github/workflows/build.yml
- docs/en/install.md
- docs/zh_cn/install.md
mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well.
> Update the installation of MMCV

- mmtrack/datasets/base_sot_dataset.py
- mmtrack/datasets/got10k_dataset.py
- mmtrack/datasets/trackingnet_dataset.py
We speed up SOT test by avoiding reloading the files of video information repeatedly in all frames of one video.
> [Enhancement] Speed up SOT test

- mmtrack/models/aggregators/selsa_aggregator.py
see https://github.com/open-mmlab/mmtracking/issues/370
see https://github.com/open-mmlab/mmtracking/pull/375
(sorry for the double pr)
> [FIX] Support empty tensor for selsa_aggregator

- tests/test_models/test_forward/test_mot_forward.py
see https://github.com/open-mmlab/mmdetection/pull/7449/files#diff-0316f6748b9914ca9ee0f99af3d4f925d6b2005a887f84c35b7c7454c33ab330
`weight_reduce_loss` fix a bug when `avg_factor == 0`
> [FIX] Fix a bug in unittest

- requirements/runtime.txt
We limit `scipy<=1.7.3` and `pandas<=1.3.5`, since both `scipy>1.7.3` and `pandas>1.3.5` requires `python>=3.8`
> [FIX] Limit the version of scipy and pandas

- mmtrack/models/track_heads/roi_embed_head.py
**Bug Fixes**
In Pytorch 1.11, `F.cross_entropy` only allows the labels with the type of `int64` rather than `int32`. We fix the bug in the `get_target()` function of `roi_embed_head.py`.
> [Fix] Change the type of `label` from `int32` to `int64` in the args of `F.cross_entropy` for pytorch 1.11

- mmtrack/apis/inference.py
Windows does not allow processes other than the one used to create the `NamedTemporaryFile` to access the file when using delete=True (the default).  So we remove the temporary file created before manually.
The problem can be seen on this issue: https://github.com/open-mmlab/mmtracking/issues/524
> [Fix] Fix a bug about the permission of temporary file on Win

- README.md
- README_zh-CN.md
It should be helpful to gain more attention of potential users and contributors by emphasizing the development roadmap in README.
> [Doc] link development roadmap in README

- mmtrack/models/trackers/byte_tracker.py
add multi-class multi-object tracking support in ByteTrack based on the `labels` segments given in detections.
It would be trivial to extend this feature to other trackers.
> [Feature] Support multi-class tracking in ByteTrack

- README.md
- README_zh-CN.md
I remake the gallery for supported/on-the-way methods and datasets in the README.
We should discuss the aesthetic preference of this version. I use emoji ⭕ and ✅ to indicate on-the-way and already supported entries. This is a workaround because the raw html tags `<input type="checkbox" />` and `<input type="checkbox"  checked />` for checkbox in the table are not supported by Github markdown standard. There are other alternatives such as ✔️. Or, we could make the table pure HTML coded instead of a markdown table, which will nicely support in-table checkbox.
> [Doc] Edit benchmark gallery in README

- docs/en/conf.py
By default, myst-parser did not parse links to anchor tags in markdown files, making these hyperlinks become raw texts in docs. This PR updates myst's configuration to enable this feature.
> [Docs] Configure Myst-parser to parse anchor tag

- configs/mot/qdtrack/qdtrack_faster-rcnn_r101_fpn_24e_lvis.py
It is mainly to modify `config.py` to inherit directly from `fast_ rcnn_ r50_ fpn`，
Inherited from `qdtrack_faster-rcnn_r50_ fpn_ 4e_ base` will be inconvenient to modify some configuration keys, especially in the `detector` part, which directly inherits` fast_ rcnn_ r50_ fpn` feels more friendly.
At present, the cfg of the `master` branch will lead to differences in track AP on Tao (11.0/8.5).
> [Fix] Fix a bug in the configuration file of QDTrack on LVIS dataset.

- README.md
- README_zh-CN.md
- docs/en/model_zoo.md
- docs/zh_cn/model_zoo.md
- model-index.yml
update document to reflect the support of OC-SORT.
> [Doc] Update document to reflect the support of OC-SORT.

- tools/train.py
As shown in  
https://github.com/open-mmlab/mmcv/blob/04ec054e6b32f31b7f475304828706dc70844972/mmcv/runner/base_runner.py#L387
, `cfg.gpu_ids` are used to calculate `self._iter`  when resuming checkpoint in distributed train. But it is set to `range(1)` by default, which lead to incorrect `self._iter` and potentially cause incorrect values which are calculated based on `runner.iter` (e.g., the learning rate in some lr scheduler.)
Similar bug has been found and fixed in mmseg (https://github.com/open-mmlab/mmsegmentation/pull/866#issue-992831656)
> [Fix] Fix bugs about cfg.gpu_ids in distributed training

- mmtrack/models/motion/camera_motion_compensation.py
- mmtrack/models/trackers/strongsort_tracker.py
- mmtrack/models/trackers/tracktor_tracker.py
This PR fixes some bugs in the CMC model according to #763.
To be specific:
- fix v1: The original cmc model only change the `track.bboxes`, rather than `track.mean`, which means CMC will don't influence the stage-1 association of StrongSORT. Therefore, I add the missing modifications on `track.mean` in this PR.
- fix v2: According to the codes from mmcv, https://github.com/open-mmlab/mmcv/blob/5f58b9101f959a5794860b2737ab83b522d25915/mmcv/transforms/loading.py#L69-L71 and https://github.com/open-mmlab/mmcv/blob/5f58b9101f959a5794860b2737ab83b522d25915/mmcv/image/io.py#L212-L215, the input image is of BGR type. However, it is treated as RGB in CMC. Therefore, I fix it.
- fix v3: Because the img is resized in test_pipeline, we need to rescale the warp_matrix while applyint CMC model.
The …
> [Fix] Fix bugs in CMC model

- mmtrack/apis/train.py
- mmtrack/utils/__init__.py
- mmtrack/utils/util_distribution.py
- tools/test.py
- tools/train.py
Added ascending device support in mmtracking.
The main modification points are as follows:
We added an NPU device in the DDP scenario and DP scenario when using the NPU.
We tested configs/reid/resnet50_b32x8_MOT17.py  in the DDP scenario and DP scenario.
cuda: 
train
test
npu:
train
test
cpu:
train
test
> [Feature] Support mmtrack with NPU backend.
