open-mmlab/mmtracking

mmtrack/models/mot/base.py

fix with_motion bug

---

demo/demo_mot.py
mmtrack/core/utils/visualization.py
mmtrack/models/mot/base.py

When running `demo_mot.py` with `--show`, the demo is blocked...
Add `wait_time` for `BaseMultiObjectTracker.show_result`

Add `wait_time` for MOT.

---

docs/tutorials/config.md

Changed from Inllustrated to Illustrated. Nothing major

Minor spelling mistake

---

.github/workflows/build.yml

This PR modifys the installation method of mmcv-full. Refer to https://github.com/open-mmlab/mmdetection/blob/master/.github/workflows/build.yml#L60 
@zhouzaida

[Fix] modify mmcv-full installation

---

mmtrack/core/evaluation/eval_hooks.py
mmtrack/datasets/builder.py
mmtrack/datasets/pipelines/formatting.py
mmtrack/datasets/reid_dataset.py

This PR fix following bug:
1. add `flag` in `ReIDDataset`
2. determine if attribute `load_as_video` exists before using `load_as_video`
3. use 'Sequence' type to stack array.

[Fix] fix some bug for reid training

---

configs/_base_/datasets/mot_challenge_reid.py
configs/mot/tracktor/README.md
configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private-half.py
configs/reid/resnet50_b32*8_MOT17.py

This PR adds the reid training config, and updates the benchmark of tracktor.

Update the benchmark of Tracktor

---

docs_zh-CN/install.md

add docs_zh-CN/install.md

---

configs/_base_/datasets/mot_challenge_reid.py

This PR modefiy the path of the reid images in configs.

[Fix] fix ReID training config

---

tools/publish_model.py

This PR modified `tools/publish_model.py` in order to add model time into the name of published model and copy training log.json

Modify tools/publish_model.py

---

docs_zh-CN/changelog.md
docs_zh-CN/tutorials/config.md
docs_zh-CN/tutorials/config_mot.md
docs_zh-CN/tutorials/config_sot.md
docs_zh-CN/tutorials/config_vid.md
docs_zh-CN/tutorials/customize_dataset.md
docs_zh-CN/useful_tools_scripts.md

This RP adds seven chinese documentations as follow

[Docs] Add chinese docs

---

.github/workflows/build.yml
.github/workflows/lint.yml
configs/sot/siamese_rpn/metafile.yml

This PR mainly contains the following:
1. Cancel previous runs that are not completed
2. Update siamrpn++ metafile.

[CI] Cancel previous runs that are not completed

---

mmtrack/__init__.py
mmtrack/apis/train.py

We support CPU training.
Please refer to open-mmlab/mmdetection#7016

Support CPU training

---

tools/test.py
tools/train.py

Please refer to open-mmlab/mmdetection#7019

Fix bug in non-distributed multi-gpu training/testing

---

configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot20-private-half.py

[Fix] Fix a bug in the config of ByteTrack on MOT20 dataset

---

docs/en/tutorials/config_mot.md
docs/en/tutorials/config_sot.md
docs/en/tutorials/config_vid.md
docs/zh_cn/tutorials/config_mot.md
docs/zh_cn/tutorials/config_sot.md
docs/zh_cn/tutorials/config_vid.md

It's a few lines modified to add more logger hooks to docs.

Logger Hooks Config Updated in Docs

---

docs/zh_cn/dataset.md

Correct a tiny error in dataset.md.

[Docs] a tiny error in dataset.md

---

README.md
README_zh-CN.md

add MMYOLO desc in README.md
add MMYOLO desc in README.md
None
None

add MMYOLO description in README

---

.github/workflows/build.yml

Fix the installation of pycocotools like https://github.com/open-mmlab/mmaction2/pull/1831

[CI] Fix the installation of pycocotools

---

README.md
README_zh-CN.md
configs/sot/mixformer/README.md
configs/sot/mixformer/metafile.yml
configs/sot/mixformer/mixformer_cvt_500e_got10k.py
configs/sot/mixformer/mixformer_cvt_500e_trackingnet.py
docs/en/model_zoo.md
docs/zh_cn/model_zoo.md
mmtrack/models/sot/mixformer.py
model-index.yml

Google drive: https://drive.google.com/drive/folders/1FFlkkN3IOGABzxmy1LxskxEzvD1pQ2Ov?usp=sharing
lasot and trackingnet use the same model checkpoint mixformer_cvt_mmtrack.pth
got10k-only checkpoint mixformer_cvt_got10k_mmtrack.pth

Provide checkpoints for MixFormer.

---

docs/zh_cn/get_started.md
docs/zh_cn/user_guides/6_analysis_tools.md

#780  Translate 'get_start.md' and 'analysis.md' into Chinese, and fix issues in #786

[Docs] `get_started.md` and `analysis_tools.md`.

---

docs/en/user_guides/2_dataset_prepare.md

Adding OpenDataLab download link in 'docs/en/user_guides/2_dataset_prepare.md'.

[Docs] Adding OpenDataLab download link
